# Generated by Django 5.1.4 on 2025-03-14 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('currency_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'currencies',
            },
        ),
        migrations.AlterField(
            model_name='exchangeratenormalized',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.currency'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.currency'),
        ),
    ]
